spring.application.name=spring-registry

server.port=8761
eureka.instance.hostname=localhost
server.servlet.context-path=/registry

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.default.zone=true