spring.application.name=payment-service


server.servlet.context-path=/payment

server.port=8011
#writen below part in github
#eureka.client.service-url.defaultZone=http://localhost:8761/registry/eureka

spring.config.import=optional:configserver:http://localhost:9999/configserver
#spring.datasource.url= jdbc:postgresql://localhost:5432/services
#spring.datasource.username=postgres
#spring.datasource.password=root
#
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true